services:
  - type: web
    name: attrition-backend
    env: python
    buildCommand: uv sync
    startCommand: cd attrition-backend && uv run app.py
    envVars:
      - key: PORT
        value: 8000
    plan: free
    autoDeploy: true
    repo: https://github.com/maanu-v/attrition-analytics
    branch: main
    rootDir: .

  - type: web
    name: attrition-frontend
    env: node
    buildCommand: cd attrition-frontend && npm install
    startCommand: cd attrition-frontend && npm run dev
    plan: free
    autoDeploy: true
    repo: https://github.com/maanu-v/attrition-analytics
    branch: main
    rootDir: .
