services:
  - type: web
    name: attrition-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn attrition-backend.main:app --host 0.0.0.0 --port 8000
    envVars:
      - key: PORT
        value: 8000
    plan: free
    autoDeploy: true
    repo: https://github.com/maanu-v/attrition-analytics
    branch: main
    rootDir: attrition-backend

  - type: web
    name: attrition-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: out
    plan: free
    autoDeploy: true
    repo: https://github.com/maanu-v/attrition-analytics
    branch: main
    rootDir: attrition-frontend
